// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu0KRr4sOWvArK0IT6fcLyaxzczxEc-X0',
    appId: '1:255404257486:web:bef406e5e77083ce91609f',
    messagingSenderId: '255404257486',
    projectId: 'event-management-a3331',
    authDomain: 'event-management-a3331.firebaseapp.com',
    storageBucket: 'event-management-a3331.appspot.com',
    measurementId: 'G-M1X8NW2M5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-0jzR4RQKQgkwp58DTDYQdnYAlqA53lQ',
    appId: '1:255404257486:android:8db03a0922a3877c91609f',
    messagingSenderId: '255404257486',
    projectId: 'event-management-a3331',
    storageBucket: 'event-management-a3331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiBF70V00BNjnwYNED58PHPU75wgoCrYA',
    appId: '1:255404257486:ios:474686e14d7c376b91609f',
    messagingSenderId: '255404257486',
    projectId: 'event-management-a3331',
    storageBucket: 'event-management-a3331.appspot.com',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiBF70V00BNjnwYNED58PHPU75wgoCrYA',
    appId: '1:255404257486:ios:fb0144e99d3f12ea91609f',
    messagingSenderId: '255404257486',
    projectId: 'event-management-a3331',
    storageBucket: 'event-management-a3331.appspot.com',
    iosBundleId: 'com.example.eventManagement.RunnerTests',
  );
}
